os:
  - linux

language: python

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10"
    - python: nightly
    - python: pypy3
  allow_failures:
    - python: "3.10"
    - python: nightly
    - python: pypy3

install:
  - make install-packages
  - pip install python-coveralls

script:
  - make check
  - nosetests
  - coverage run --source=. -m unittest discover

after_success:
  - coveralls
